import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/home1">Home1</Link>
        </li>
        <li>
          <Link to="/live">Live</Link>
        </li>
        <li>
          <Link to="/casino">Casino</Link>
        </li>
        <li>
          <Link to="/esports">Esports</Link>
        </li>
        <li>
          <Link to="/prematch">Prematch</Link>
        </li>
        <li>
          <Link to="/tournaments">Tournaments</Link>
        </li>
        <li>
          <Link to="/livecasino">Livecasino</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
